from build_tools import *

group = []

if not IsDefined(['NUMDL_FEATURE']):
    Return('group')

pwd = PresentDir()

path = [pwd]
src = []

src += Glob('*.cc')
src += Glob('*.c')

group = AddCodeGroup('numdl', src, depend = ['NUMDL_FEATURE'], CPPPATH = path)

Return('group')