from build_tools import *

group = []

if not IsDefined(['UAI_USING_AUDIO_FEATURE_FUNC']):
    Return('group')

pwd = PresentDir()

path = [pwd]
src = []

src += Glob('*.cc')

group = AddCodeGroup('uai', src, depend = ['UAI_USING_AUDIO_FEATURE_FUNC'], CPPPATH = path)

Return('group')