from build_tools import *

group = []

if not IsDefined(['NUMDL_USING_TEST']):
    Return('group')

pwd = PresentDir()

path = [pwd]
src = []

if IsDefined(['NUMDL_TEST_USING_MATRIX_TC']):
    src += Glob('common/uai_matrix_tc.c')

if IsDefined(['NUMDL_TEST_USING_FEATURE_TC']):
    src += Glob('feature/*.cc')
    src += Glob('feature/testdata/*.c')

group = AddCodeGroup('numdl', src, depend = ['NUMDL_USING_TEST'], CPPPATH = path)

Return('group')
