from build_tools import *

group = []

if not IsDefined(['UAI_USING_TEST']):
    Return('group')

pwd = PresentDir()

path = [pwd]
src = []

if IsDefined(['UAI_TEST_USING_MATRIX_TC']):
    src += Glob('common/uai_matrix_tc.c')

if IsDefined(['UAI_USING_AUDIO_FEATURE_TC']):
    src += Glob('feature/*.cc')
    src += Glob('feature/testdata/*.c')

group = AddCodeGroup('uai', src, depend = ['UAI_USING_TEST'], CPPPATH = path)

Return('group')
