from build_tools import *

group = []

if not IsDefined(['NUMDL_CANDY']):
    Return('group')

pwd = PresentDir()
path  = [pwd]

#list = os.listdir(pwd)
#for item in list:
#    if os.path.isdir(os.path.join(pwd, item)):
#        path.append(os.path.join(pwd, item))

src = []
src += Glob('*.cc')
src += Glob('*.c')

group = AddCodeGroup('numdl', src, depend = ['NUMDL_CANDY'], CPPPATH = path)

Return('group')